{% set name = "unicorn-fy" %}
{% set version = "0.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicorn_fy-{{ version }}.tar.gz
  sha256: 5de8f40580651169a27ebe598f2ebce91ac78147a4c5eeda3448c23bde404275

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - mypy
  run:
    - python
    - cython
    - orjson
    - requests

test:
  imports:
    - unicorn_fy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oliver-zehentleitner/unicorn-fy
  summary: Normalizes raw responses from crypto exchange APIs into consistent Python dictionaries.
  description: |
    UnicornFy normalizes raw responses from crypto exchange APIs (Binance & co.)
    into consistent, cleanly-typed Python dictionaries. A transformation layer
    that makes exchange data interchangeable instead of exchange-specific.
    Part of the UNICORN Binance Suite.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/oliver-zehentleitner/unicorn-fy
  doc_url: https://oliver-zehentleitner.github.io/unicorn-fy

extra:
  recipe-maintainers:
    - oliver-zehentleitner
