{% set name = "unicorn-fy" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-fy-{{ version }}.tar.gz
  sha256: b51196e661a6b326fbe588af56c8e41aee1b328e4ea1a5c215c91c72a885c60f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - requests
    - ujson
  run:
    - python >=3.6
    - requests
    - ujson

test:
  imports:
    - unicorn_fy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-fy.html
  summary: Convert received raw data from crypto exchange API endpoints into well-formed python dictionaries.
  description: |
    Convert received raw data from crypto exchange API endpoints into well-formed python dictionaries.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-fy
  doc_url: https://unicorn-fy.docs.lucit.tech/

extra:
  recipe-maintainers:
    - oliver-zehentleitner
