{% set name = "unicorn-fy" %}
{% set version = "0.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5de8f40580651169a27ebe598f2ebce91ac78147a4c5eeda3448c23bde404275

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - requests
    - ujson
  run:
    - python >=3.6
    - requests
    - ujson

test:
  imports:
    - unicorn_fy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-fy.html
  summary: Convert received raw data from crypto exchange API endpoints into well-formed python dictionaries.
  description: |
    Convert received raw data from crypto exchange API endpoints into well-formed python dictionaries.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-fy
  doc_url: https://unicorn-fy.docs.lucit.tech/

extra:
  recipe-maintainers:
    - oliver-zehentleitner
